os: linux

dist: bionic

language: python

python:
  - 3.6
  - 3.7
  - 3.8

node_js:
  - 12

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - npm install -g yarn
  - apt-get install geckodriver

before_script:
  - (cd hub_app/static/hub_app/managed && yarn install)
  - ./manage.py collectstatic --no-input

script:
  - coverage run --rcfile=.coveragerc.ini manage.py test --settings=hub.ci_settings
  - coverage report --rcfile=.coveragerc.ini
  - flake8 --statistics --config=.flake8.ini .
  - pylint --rcfile=.pylint.ini hub hub_app
  - bandit -r ./

cache: pip
