# Generated by Django 3.0.3 on 2020-02-24 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hub_app.accountlib.email
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hub_app', '0003_pendingcredentialrecovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingEMailChange',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('new_email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('valid_until', models.DateTimeField(default=hub_app.accountlib.email.get_email_max_validity, verbose_name='Valid Until')),
                ('key', models.CharField(default=hub_app.accountlib.email.get_email_key, max_length=255, verbose_name='E_Mail Change Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Pending E-Mail Change',
                'verbose_name_plural': 'Pending E-Mail Changes',
                'permissions': (),
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
